// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/address-book.proto

package protos;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protos.Person people = 1;</code>
   */
  java.util.List<protos.Person> 
      getPeopleList();
  /**
   * <code>repeated .protos.Person people = 1;</code>
   */
  protos.Person getPeople(int index);
  /**
   * <code>repeated .protos.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .protos.Person people = 1;</code>
   */
  java.util.List<? extends protos.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .protos.Person people = 1;</code>
   */
  protos.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
